export enum BalanceEvents {
  CAMPAIGN_AFTER_CAMPAIGN_PUBLISH = 'CAMPAIGN_AFTER_CAMPAIGN_PUBLISH',
  CAMPAIGN_AFTER_CAMPAIGN_PUBLISH_ERROR = 'CAMPAIGN_AFTER_CAMPAIGN_PUBLISH_ERROR',
  CAMPIIGNER_BALANCE_AFTER_TOPUP = 'CAMPIIGNER_BALANCE_AFTER_TOPUP',
}
