export enum CampaignEvents {
    CAMPAIGN_PUBLISH_CONTENT = "CAMPAIGN_PUBLISH_CONTENT",
    CAMPAIGN_PUBLISH_DO_SM_TRANSACTION = "CAMPAIGN_DO_SM_TRANSACTION",
    CAMPAIGN_PUBLISH_ERROR = "CAMPAIGN_PUBLISH_ERROR",
} 