export enum CampaignEvents {
    CAMPAIGN_DRAFTED = "CAMPAIGN_DRAFTED",
    CAMPAIGN_APPROVED = "CAMPAIGN_APPROVED",
    CAMPAIGN_REJECTED = "CAMPAIGN_REJECTED",
    CAMPAIGN_INITIATE_PUBLISH = "CAMPAIGN_INITIATE_PUBLISH",
    CAMPAIGN_PUBLISHED = "CAMPAIGN_PUBLISHED",
    CAMPAIGN_UNPUBLISHED = "CAMPAIGN_UNPUBLISHED",
    CAMPAIGN_CLOSED = "CAMPAIGN_CLOSED",
    CAMPAIGN_ARCHIVED = "CAMPAIGN_ARCHIVED",
} 