openapi: 3.0.0
info:
  title: X API Rate Limiting System
  version: 1.0.0
paths:
  /campaigns:
    post:
      summary: Submit new campaign
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignJob'
      responses:
        '200':
          description: Success
  /campaigns/{id}:
    get:
      summary: Get campaign status and results
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /pools:
    get:
      summary: View current rate limit states
      responses:
        '200':
          description: Success
  /stats:
    get:
      summary: System usage metrics and health
      responses:
        '200':
          description: Success
  /tenants/{id}/quota:
    get:
      summary: Tenant-specific quotas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Success
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: Success
components:
  schemas:
    CampaignJob:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [Quest, Awareness]
        tweetId:
          type: string
        tenant:
          type: string
        priority:
          type: integer
        scheduledWindow:
          type: integer
